# Generated by Django 4.1.4 on 2023-01-26 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='biography_books',
            new_name='best_sellers',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='business_books',
            new_name='liked_by_critics',
        ),
    ]
